version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: shido
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: vehicle-sales-manager
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
